class_name CardID

const SENHA_FORTE := "senha_forte"
const AUTENTICACAO_2FA := "autenticacao_2fa"
const REUTILIZAR_SENHA := "reutilizar_senha"
const LINK_SUSPEITO := "link_suspeito"
const SENHAS_EXCLUSIVAS := "senhas_exclusivas"
const ABRIR_ANEXO := "abrir_anexo"
const VERIFICAR_REMETENTE := "verificar_remetente"
const ANTIVIRUS_ATUALIZADO := "antivirus_atualizado"
const GERENCIADOR_SENHAS := "gerenciador_senhas"
const TROCAR_SENHA_VAZADA := "trocar_senha_vazada"
const PROTEGER_CODIGO := "proteger_codigo"
const SENHA_DATA_NASCIMENTO := "senha_data_nascimento"
const SENHA_COLADA_MONITOR := "senha_colada_monitor"
